### ISSUE TITLE
Final Project Submission

### ISSUE THREAD

**Issue by lorifranke** [NimilRl/VirtualExpo#1]
![FeedbackBanner](https://github.com/NimilRl/VirtualExpo/assets/38534852/4e010752-2905-47aa-b7bf-fcd15a534119)

Hello @NimilRl,

Thanks for submitting the final project! Here is some feedback on your submission:

Here are the things you did great:

- The documentation of your project is exceptional. It's detailed, clear, and well-organized, which significantly enhances the understanding and usability of your project.
- Including a video in the README is an excellent touch. It provides a dynamic and interactive way to demonstrate the functionality and features of your project.

Here are some suggestions and possible improvements:
**Code and features**
- Great idea adding the change.txt file and what features you changed and added, and also thanks for giving credit to the existing game! The code, especially the game.js file might be a bit too long for a CS460 assignment, but the game and adding features yourself is already contribution enough.

**Docs**

You've already set a high standard with your documentation. To further enrich it, consider adding more detailed descriptions or examples of how users can interact with or benefit from your project.

**Overall Thoughts**

Your project has an outstanding documentation compared to other students and the innovative inclusion of a video in the README (you were the only student adding this). These aspects not only demonstrate your technical proficiency but also your ability to effectively communicate and present your work :-) Continue to focus on these strengths in your future projects as well as maybe creating an own project from scratch. Great job, and thank you for your submission!

**Comment by NimilRl** [comment]
Thank you, ma'am. and sorry for late reply. i really appreciate your feedback and try to improve.
